//! LoRaWAN handling module
//!
//! This module provides LoRaWAN network connectivity and message transmission.

use defmt::{error, info, warn};
use embassy_sync::blocking_mutex::raw::CriticalSectionRawMutex;
use embassy_sync::mutex::Mutex;
use embassy_time::{Delay, Duration, Timer};
use esp_hal::gpio::{Input, InputConfig, Level, Output, OutputConfig};
use esp_hal::spi::master::Config;
use esp_hal::spi::master::Spi;
use esp_hal::spi::Mode;
use esp_hal::time::Rate;
use esp_hal::Async;
use lora_phy::iv::GenericSx126xInterfaceVariant;
use lora_phy::sx126x;
use lora_phy::sx126x::Sx1262;
use lora_phy::sx126x::Sx126x;
use lora_phy::sx126x::TcxoCtrlVoltage;
use lora_phy::LoRa;
use lora_phy::lorawan_radio::LorawanRadio;
use lorawan_device::async_device::{region, Device, JoinMode, JoinResponse};
use lorawan_device::default_crypto::DefaultFactory as Crypto;
use lorawan_device::{AppEui, AppKey, DevEui};
use static_cell::StaticCell;

use crate::{victron_payload, generate_delay, SimpleTimer, VictronDeviceStorage};

// LoRaWAN configuration constants
const LORAWAN_REGION: region::Region = region::Region::EU868;
const MAX_TX_POWER: u8 = 14;

// Load optional override values for EUIs and APPKEY generated by build.rs from
// environment values
include!(concat!(env!("OUT_DIR"), "/lorawan_keys.rs"));

// Fallback values
const DEFAULT_DEVEUI: [u8; 8] = [0, 0, 0, 0, 0, 0, 0, 0];
const DEFAULT_APPEUI: [u8; 8] = [0, 0, 0, 0, 0, 0, 0, 0];
const DEFAULT_APPKEY: [u8; 16] = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];

// Static SPI bus shared between tasks
static SPI_BUS: StaticCell<
    Mutex<CriticalSectionRawMutex, esp_hal::spi::master::Spi<'static, Async>>,
> = StaticCell::new();

/// LoRaWAN task - handles network joining and data transmission
#[embassy_executor::task]
pub async fn lorawan_task(
    device_storage: &'static Mutex<CriticalSectionRawMutex, VictronDeviceStorage>,
) {
    info!("LoRaWAN task starting...");

    // Wait a bit for system to initialize
    Timer::after(Duration::from_secs(2)).await;

    // Steal peripherals for LoRa radio (SPI already initialized by main)
    // We'll initialize SPI here since it's needed only for LoRaWAN
    let peripherals = unsafe { esp_hal::peripherals::Peripherals::steal() };

    let nss = Output::new(peripherals.GPIO8, Level::High, OutputConfig::default());
    let sclk = peripherals.GPIO9;
    let mosi = peripherals.GPIO10;
    let miso = peripherals.GPIO11;

    let reset = Output::new(peripherals.GPIO12, Level::Low, OutputConfig::default());
    let busy = Input::new(peripherals.GPIO13, InputConfig::default());
    let dio1 = Input::new(peripherals.GPIO14, InputConfig::default());

    let spi = Spi::new(
        peripherals.SPI2,
        Config::default()
            .with_frequency(Rate::from_khz(100))
            .with_mode(Mode::_0),
    )
    .unwrap()
    .with_sck(sclk)
    .with_mosi(mosi)
    .with_miso(miso)
    .into_async();

    // Initialize the static SPI bus
    let spi_bus = SPI_BUS.init(Mutex::new(spi));
    let spi_device = embassy_embedded_hal::shared_bus::asynch::spi::SpiDevice::new(spi_bus, nss);

    // Create the SX126x configuration
    let sx126x_config = sx126x::Config {
        chip: Sx1262,
        tcxo_ctrl: Some(TcxoCtrlVoltage::Ctrl1V7),
        use_dcdc: true,
        rx_boost: false,
    };

    // Create the radio instance
    let iv = GenericSx126xInterfaceVariant::new(reset, dio1, busy, None, None).unwrap();
    let lora = LoRa::new(Sx126x::new(spi_device, iv, sx126x_config), true, Delay)
        .await
        .unwrap();

    let radio: LorawanRadio<_, _, MAX_TX_POWER> = lora.into();
    let region: region::Configuration = region::Configuration::new(LORAWAN_REGION);
    let rng = esp_hal::rng::Rng::new();
    let mut rng2 = esp_hal::rng::Rng::new(); // Separate RNG for delay generation
    let timer = SimpleTimer::new();
    let mut device: Device<_, Crypto, _, _> = Device::new(region, radio, timer, rng);

    let mut deveui = DEVEUI.unwrap_or(DEFAULT_DEVEUI);
    deveui.reverse();
    let appeui = APPEUI.unwrap_or(DEFAULT_APPEUI);
    let appkey = APPKEY.unwrap_or(DEFAULT_APPKEY);

    info!("LoRaWAN Credentials:");
    info!("  DevEUI: {:#x}", deveui);
    info!("  AppEUI: {:#x}", appeui);
    info!("  AppKey: {:#x}", appkey);
    info!("Joining LoRaWAN network");

    let join_mode = JoinMode::OTAA {
        deveui: DevEui::from(deveui),
        appeui: AppEui::from(appeui),
        appkey: AppKey::from(appkey),
    };

    let mut retries = 0;

    loop {
        let join_result = device.join(&join_mode).await;
        match join_result {
            Ok(JoinResponse::JoinSuccess) => {
                info!("LoRaWAN network joined");
                break;
            }
            Ok(JoinResponse::NoJoinAccept) => {
                warn!("LoRaWAN network did not accept");
            }
            Err(e) => {
                error!("Error joining LoRaWAN network: {}", e)
            }
        }
        let delay = generate_delay(&mut rng2, retries);

        info!("Join failed. Retrying in {} seconds..", delay);
        Timer::after(Duration::from_secs(delay.into())).await;
        retries += 1;
    }

    info!("LoRaWAN network joined!");

    let mut payload_buffer = [0u8; 51]; // EU868 max payload

    loop {
        // Get next device from storage (round-robin)
        info!("LoRaWAN: Getting next device from storage...");

        // Pack device data while holding the lock (DeviceData isn't Copy)
        let packed_result = {
            let mut storage = device_storage.lock().await;
            if let Some(entry) = storage.get_next_valid_device() {
                let mac = entry.mac_address;
                let rssi = entry.rssi;
                let len = victron_payload::pack_device_with_metadata(
                    &mac,
                    rssi,
                    &entry.data,
                    &mut payload_buffer,
                );
                Some((mac, rssi, len))
            } else {
                None
            }
        };

        if let Some((mac, rssi, len)) = packed_result {
            info!(
                "Sending device: MAC={:02x}:{:02x}:{:02x}:{:02x}:{:02x}:{:02x}, RSSI={}",
                mac[0],
                mac[1],
                mac[2],
                mac[3],
                mac[4],
                mac[5],
                rssi
            );

            if len == 0 {
                warn!("Failed to pack device data");
            } else {
                info!("Sending Victron data: {} bytes (MAC:6 + RSSI:1 + Type:1 + Data:{})", len, len - 8);
                let data = &payload_buffer[..len];
                let fport = 2; // Port 2 for Victron data
                let confirmed = false; // Use unconfirmed uplink

                // Send the message
                match device.send(data, fport, confirmed).await {
                    Ok(response) => {
                        info!("Message sent successfully: {:?}", response);

                        // Check for downlink messages
                        if let Some(downlink) = device.take_downlink() {
                            info!(
                                "Received downlink on port {}, {} bytes",
                                downlink.fport,
                                downlink.data.len()
                            );
                        }
                    }
                    Err(e) => {
                        error!("Failed to send message: {}", e);
                    }
                }
            }
        } else {
            info!("LoRaWAN: No valid devices in storage");
        }

        // Wait 60 seconds before next transmission (respect duty cycle)
        info!("Waiting 60 seconds before next transmission...");
        Timer::after(Duration::from_secs(60)).await;
    }
}
