//! LoRaWAN handling module
//!
//! This module provides LoRaWAN network connectivity and message transmission.

use defmt::{error, info, warn};
use embassy_sync::blocking_mutex::raw::CriticalSectionRawMutex;
use embassy_sync::channel::Channel;
use embassy_sync::mutex::Mutex;
use embassy_time::{Delay, Duration, Timer};
use esp_hal::gpio::{Input, InputConfig, Level, Output, OutputConfig};
use esp_hal::spi::master::Config;
use esp_hal::spi::master::Spi;
use esp_hal::spi::Mode;
use esp_hal::time::Rate;
use esp_hal::Async;
use lora_phy::iv::GenericSx126xInterfaceVariant;
use lora_phy::sx126x;
use lora_phy::sx126x::Sx1262;
use lora_phy::sx126x::Sx126x;
use lora_phy::sx126x::TcxoCtrlVoltage;
use lora_phy::LoRa;
use lora_phy::lorawan_radio::LorawanRadio;
use lorawan_device::async_device::{region, Device, JoinMode, JoinResponse};
use lorawan_device::default_crypto::DefaultFactory as Crypto;
use lorawan_device::{AppEui, AppKey, DevEui};
use static_cell::StaticCell;

use crate::{device::DeviceData, victron_payload, generate_delay, SimpleTimer};

// LoRaWAN configuration constants
const LORAWAN_REGION: region::Region = region::Region::EU868;
const MAX_TX_POWER: u8 = 14;

// Load optional override values for EUIs and APPKEY generated by build.rs from
// environment values
include!(concat!(env!("OUT_DIR"), "/lorawan_keys.rs"));

// Fallback values
const DEFAULT_DEVEUI: [u8; 8] = [0, 0, 0, 0, 0, 0, 0, 0];
const DEFAULT_APPEUI: [u8; 8] = [0, 0, 0, 0, 0, 0, 0, 0];
const DEFAULT_APPKEY: [u8; 16] = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];

// Static SPI bus shared between tasks
static SPI_BUS: StaticCell<
    Mutex<CriticalSectionRawMutex, esp_hal::spi::master::Spi<'static, Async>>,
> = StaticCell::new();

/// LoRaWAN task - handles network joining and data transmission
#[embassy_executor::task]
pub async fn lorawan_task(
    victron_channel: &'static Channel<CriticalSectionRawMutex, Option<DeviceData>, 10>,
) {
    info!("LoRaWAN task starting...");

    // Wait a bit for system to initialize
    Timer::after(Duration::from_secs(2)).await;

    // Steal peripherals for LoRa radio (SPI already initialized by main)
    // We'll initialize SPI here since it's needed only for LoRaWAN
    let peripherals = unsafe { esp_hal::peripherals::Peripherals::steal() };

    let nss = Output::new(peripherals.GPIO8, Level::High, OutputConfig::default());
    let sclk = peripherals.GPIO9;
    let mosi = peripherals.GPIO10;
    let miso = peripherals.GPIO11;

    let reset = Output::new(peripherals.GPIO12, Level::Low, OutputConfig::default());
    let busy = Input::new(peripherals.GPIO13, InputConfig::default());
    let dio1 = Input::new(peripherals.GPIO14, InputConfig::default());

    let spi = Spi::new(
        peripherals.SPI2,
        Config::default()
            .with_frequency(Rate::from_khz(100))
            .with_mode(Mode::_0),
    )
    .unwrap()
    .with_sck(sclk)
    .with_mosi(mosi)
    .with_miso(miso)
    .into_async();

    // Initialize the static SPI bus
    let spi_bus = SPI_BUS.init(Mutex::new(spi));
    let spi_device = embassy_embedded_hal::shared_bus::asynch::spi::SpiDevice::new(spi_bus, nss);

    // Create the SX126x configuration
    let sx126x_config = sx126x::Config {
        chip: Sx1262,
        tcxo_ctrl: Some(TcxoCtrlVoltage::Ctrl1V7),
        use_dcdc: true,
        rx_boost: false,
    };

    // Create the radio instance
    let iv = GenericSx126xInterfaceVariant::new(reset, dio1, busy, None, None).unwrap();
    let lora = LoRa::new(Sx126x::new(spi_device, iv, sx126x_config), true, Delay)
        .await
        .unwrap();

    let radio: LorawanRadio<_, _, MAX_TX_POWER> = lora.into();
    let region: region::Configuration = region::Configuration::new(LORAWAN_REGION);
    let rng = esp_hal::rng::Rng::new();
    let mut rng2 = esp_hal::rng::Rng::new(); // Separate RNG for delay generation
    let timer = SimpleTimer::new();
    let mut device: Device<_, Crypto, _, _> = Device::new(region, radio, timer, rng);

    let mut deveui = DEVEUI.unwrap_or(DEFAULT_DEVEUI);
    deveui.reverse();
    let appeui = APPEUI.unwrap_or(DEFAULT_APPEUI);
    let appkey = APPKEY.unwrap_or(DEFAULT_APPKEY);

    info!("LoRaWAN Credentials:");
    info!("  DevEUI: {:#x}", deveui);
    info!("  AppEUI: {:#x}", appeui);
    info!("  AppKey: {:#x}", appkey);
    info!("Joining LoRaWAN network");

    let join_mode = JoinMode::OTAA {
        deveui: DevEui::from(deveui),
        appeui: AppEui::from(appeui),
        appkey: AppKey::from(appkey),
    };

    let mut retries = 0;

    loop {
        let join_result = device.join(&join_mode).await;
        match join_result {
            Ok(JoinResponse::JoinSuccess) => {
                info!("LoRaWAN network joined");
                break;
            }
            Ok(JoinResponse::NoJoinAccept) => {
                warn!("LoRaWAN network did not accept");
            }
            Err(e) => {
                error!("Error joining LoRaWAN network: {}", e)
            }
        }
        let delay = generate_delay(&mut rng2, retries);

        info!("Join failed. Retrying in {} seconds..", delay);
        Timer::after(Duration::from_secs(delay.into())).await;
        retries += 1;
    }

    info!("LoRaWAN network joined!");

    let mut payload_buffer = [0u8; 51]; // EU868 max payload
    let mut last_sent_payload: Option<([u8; 51], usize)> = None; // Track last sent data to avoid duplicates

    loop {
        // Drain all available Victron data from channel
        info!("LoRaWAN: Checking channel for Victron data...");
        let mut messages_sent = 0;

        loop {
            // Try to get Victron data from channel (non-blocking)
            let victron_data = match victron_channel.try_receive() {
                Ok(data) => data,
                Err(_) => {
                    // Channel is empty
                    if messages_sent == 0 {
                        info!("LoRaWAN: No Victron data in channel");
                    }
                    break;
                }
            };

            if victron_data.is_none() {
                // Received None, skip this entry
                continue;
            }

            let device_data = victron_data.unwrap();

            // Pack Victron data into binary format
            let len = victron_payload::pack_device_data(&device_data, &mut payload_buffer);

            if len == 0 {
                // Fallback if packing failed
                warn!("Failed to pack Victron data, skipping this message");
                continue;
            }

            // Check if this payload is a duplicate of the last sent one
            let is_duplicate = if let Some((last_payload, last_len)) = &last_sent_payload {
                len == *last_len && &payload_buffer[..len] == &last_payload[..*last_len]
            } else {
                false
            };

            if is_duplicate {
                info!("Skipping duplicate data ({} bytes)", len);
                continue;
            }

            info!("Sending Victron data: {} bytes", len);
            let data = &payload_buffer[..len];
            let fport = 2; // Port 2 for Victron data
            let confirmed = false; // Use unconfirmed uplink

            // Send the message
            match device.send(data, fport, confirmed).await {
                Ok(response) => {
                    info!("Message sent successfully: {:?}", response);
                    messages_sent += 1;

                    // Update last sent payload to track duplicates
                    last_sent_payload = Some((payload_buffer, len));

                    // Check for downlink messages
                    if let Some(downlink) = device.take_downlink() {
                        info!("Received downlink on port {}, {} bytes",
                              downlink.fport, downlink.data.len());
                    }
                }
                Err(e) => {
                    error!("Failed to send message: {}", e);
                }
            }
        }

        // Report on messages sent
        if messages_sent > 0 {
            info!("Sent {} message(s) from channel", messages_sent);
        }

        // Wait 60 seconds before next transmission (respect duty cycle)
        info!("Waiting 60 seconds before next transmission...");
        Timer::after(Duration::from_secs(60)).await;
    }
}
