name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  build-root:
    name: Build (root workspace)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build root workspace
      run: cargo build --verbose
    - name: Run tests (root workspace)
      run: cargo test --verbose

  build-cross:
    name: Build (cross workspace)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install ESP toolchain using espup
      run: |
        curl -L https://github.com/esp-rs/espup/releases/latest/download/espup-x86_64-unknown-linux-gnu -o espup
        chmod a+x espup
        espup install
        source $HOME/export-esp.sh

    - name: Build
      run: |
        cargo build --verbose
    - name: Build cross workspace
      run: |
        cd cross
        cargo build --verbose
    - name: Run tests (cross workspace)
      run: |
        cd cross
        cargo test --verbose
