name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  build-root:
    name: Build (root workspace)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build root workspace
      run: cargo build --verbose
    - name: Run tests (root workspace)
      run: cargo test --verbose

  build-cross:
    name: Build (cross workspace)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Rust for Xtensa
      uses: esp-rs/xtensa-toolchain@v1.5
      with:
          default: true
          version: "latest"
          ldproxy: true

    - name: Build
      run: |
        cargo build --verbose
    - name: Build cross workspace
      run: |
        cd cross
        cargo build --verbose
    - name: Run tests (cross workspace)
      run: |
        cd cross
        cargo test --verbose
